### ISSUE TITLE
Missing extension op definitions

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/guppylang#391]
Followup to #366. We define many ad-hoc operations as opaque ops in a "guppylang.unsupported".
Some of these are missing from hugr's std extensions, or not exposed in hugr-py. Others may need to be defined as local extensions.

- [x] `list` and `array` ops. (`MakeList`, see other ops in `guppylang.prelude.builtins`)
  - [x] Add list ops to hugr.
  https://github.com/CQCL/hugr/issues/1467
  - [x] Add array ops to hug.
  https://github.com/CQCL/hugr/issues/1320
  - [x] Convert between `usize` and `int<N>`.
  https://github.com/CQCL/hugr/issues/1472
  - [x] #460
- [x] https://github.com/CQCL/guppylang/issues/411.
  - [x] https://github.com/CQCL/hugr/pull/1463
  - [x] Add missing float `fround` / `fpow` ops to hugr.
  - [x] Add missing int `ipow` / `iu_to_s` / `is_to_u` ops to hugr.
  - [x] #412
- [x] #409
  - [x] #281
- [x] #410
- [x] Tket2 ops.
  - [x] ~~https://github.com/CQCL/tket2/issues/556~~ Temporarily hard-coded the extension jsons into guppy
  - [x] #390
